### ISSUE TITLE
Observe on null-value causes onError 

### ISSUE THREAD

**Issue by Maradox** [nmoskalenko/rxFirebase#9] opened 2016-08-26 21:07 UTC
When observing with e.g.: `observeValue` and the observed value is null - `onError` is called.
Thus a route which doesn't exist at the moment of the subscription cannot be observed anymore - which should not be the case in my opinion.

This behavior is the same for all observe operators.

**Comment by ahaverty** [comment] 2016-08-27 09:36
I've been having the same problems as @Maradox on both repos @renanferrari @nmoskalenko. Unfortunately my project's design needs to listen to references that can be null or full of objects. I can use the Datasnapshot.class to get around it, check if the returned datasnapshot.exists() and get the value after that, but I'd imagine it's possible to do so from within this package? Just return a null if the reference was null?

**Comment by renanferrari** [comment] 2016-08-27 20:18
Throwing the error in this situation is the current expected behavior, but I do agree that maybe it shouldn't be.

@nmoskalenko Thoughts on this?

**Comment by nmoskalenko** [comment] 2016-08-31 13:07
I don't quite realize for myself the usecase of why somebody would want to "listen to nulls".
@ahaverty , @Maradox , could you please explain. what behaviour are you expecting for this?

**Comment by Maradox** [comment] 2016-08-31 13:30
Example: The app should monitor his own user in order to show the name of the user in the UI.
When the app starts and the user signs in the app begins to monitor his own user. At that moment the user does not exist in the firebase database, because the user did not set his name yet. When he sets his name, the object is created in the firebase database and the UI should update the name.

`
{
    "users:" {
        USER_ID : {
            "name": "Steven"
        }
    }
}
`

Expected behavior: Emit null when there is no user at that path.

**Comment by shivam0x** [comment] 2016-09-09 12:46
I think its the same problem for which I've opened an issue. 
Here also we are first we are showing all the posts by the user but it goes into onError because there is no posts reference in firebase till now. So basically if there are no posts I'm giving an option to add posts and all the logic is in onNext but it never goes into onNext. 
Going back to Firebase provided API's to see if same thing happens there.

**Comment by nmoskalenko** [comment] 2016-09-10 01:36
Fixed in 0.13, please check

**Closed as completed by nmoskalenko** 2016-09-10 01:36 UTC
